In [1]:
import torch
import sys
import os.path as osp
import os
import sys
import numpy as np

sys.path.append("/afs/cern.ch/work/m/mgarciam/private/Tracking_wcoc/")
from src.dataset.dataset import SimpleIterDataset
from src.utils.train_utils import to_filelist
from torch.utils.data import DataLoader
#import dgl  # CPU only version for now
from tqdm import tqdm
from torch_scatter import scatter_sum
import matplotlib.pyplot as plt
import pickle
import numpy as np
import mplhep as hep


hep.style.use("CMS")
import matplotlib
matplotlib.rc('font', size=13)


/eos/experiment/fcc/ee/datasets/DC_tracking/Pythia/gun_fakeCalo_g1/reco_gun_1000.root

In [3]:
# This block is the same as 1_dataset.ipynb

#"/eos/experiment/fcc/ee/datasets/DC_tracking/Pythia_evaluation/Zcard/reco_Zcard_1.root"
datasets = {
    "test": "/eos/experiment/fcc/ee/datasets/DC_tracking/Pythia/Zcard_CLD_fakeCalo_v4/reco_Zcard_CLD_1773_mc.root",
    "train": "/eos/experiment/fcc/ee/datasets/DC_tracking/Pythia/Zcard_CLD_fakeCalo_v4/reco_Zcard_CLD_1773_mc.root",
}

class Args:
    def __init__(self, datasets):
        self.data_train = [datasets]
        self.data_val = [datasets]
        #self.data_train = files_train
        self.data_config = '/afs/cern.ch/work/m/mgarciam/private/Tracking_wcoc/config_files/config_tracking_global_vector.yaml'
        self.extra_selection = None
        self.train_val_split = 0.8
        self.data_fraction = 1
        self.file_fraction = 1
        self.fetch_by_files = False
        self.fetch_step = 1
        self.steps_per_epoch = None
        self.in_memory = False
        self.local_rank = None
        self.copy_inputs = False
        self.no_remake_weights = False
        self.batch_size = 2
        self.num_workers = 0
        self.demo = False
        self.laplace = False
        self.diffs = False
        self.class_edges = False


args = {key: Args(value) for key, value in datasets.items()}

datas = {}
files_dict = {}
for key in datasets:
    train_range = (0, args[key].train_val_split)
    train_file_dict, train_files = to_filelist(args[key], 'val')
    train_data = SimpleIterDataset(train_file_dict, args[key].data_config, for_training=False,
                                   extra_selection=args[key].extra_selection,
                                   remake_weights=True,
                                   load_range_and_fraction=(train_range, args[key].data_fraction),
                                   file_fraction=args[key].file_fraction,
                                   fetch_by_files=args[key].fetch_by_files,
                                   fetch_step=args[key].fetch_step,
                                   infinity_mode=False,
                                   in_memory=args[key].in_memory,
                                   async_load=False,
                                   name='train')
    datas[key] = train_data
    files_dict[key] = train_files

None 1
None 1


In [4]:
import plotly
import plotly.graph_objects as go
import plotly.offline as pyo
from plotly.subplots import make_subplots

In [5]:
itera = iter(train_data)

=== Restarting DataIter train, seed=None ===


In [6]:
# X1 =next(itera) 
g, y = next(itera) 


/afs/cern.ch/work/m/mgarciam/private/miniconda/miniconda3/envs/graphgps/lib/python3.10/site-packages/dgl/heterograph.py:92: DGLWarning:

Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.



In [7]:
y[:,4]

tensor([  74.,   76.,   77.,   86.,   87.,   92.,   93.,   94.,   95.,   97.,
          98.,   99.,  101.,  102.,  107.,  110.,  112.,  113.,  115.,  118.,
         120.,  131.,  132.,  133.,  695.,  697., 1098., 1266.])

In [9]:
torch.unique(g.ndata['particle_number_nomap'])

tensor([  74.,   76.,   77.,   86.,   87.,   92.,   93.,   94.,   95.,   97.,
          98.,   99.,  101.,  102.,  107.,  110.,  112.,  113.,  115.,  118.,
         120.,  131.,  132.,  133.,  695.,  697., 1098., 1266.])

In [17]:

import pandas as pd
import plotly.express as px
from src.logger.plotting_tools import shuffle_truth_colors

mask = (g.ndata['particle_number'] !=-1) 
tidx =  1*(g.ndata['particle_number'][mask]).view(-1,1)
#tidx =    1*(g.ndata['hit_link_modified'][mask].view(-1,1))+1
features =  (torch.ones_like(g.ndata['particle_number'][mask].view(-1,1)))
cellid= g.ndata['particle_number'][mask].view(-1,1)
X = g.ndata["pos_hits_xyz"][mask] #[mask]
data = {
            "X":X[:, 0].view(-1, 1).detach().cpu().numpy(),
            "Y": X[:, 1].view(-1, 1).detach().cpu().numpy(),
            "Z": X[:, 2].view(-1, 1).detach().cpu().numpy(),
            "tIdx": tidx.view(-1, 1).detach().cpu().numpy(),
            "features": features.view(-1, 1).detach().cpu().numpy(),
            "cellid":cellid.view(-1, 1).detach().cpu().numpy(),
        }
hoverdict = {}
# if hoverfeat is not None:
#     for j in range(hoverfeat.shape[1]):
#         hoverdict["f_" + str(j)] = hoverfeat[:, j : j + 1]
#     data.update(hoverdict)

# if nidx is not None:
#     data.update({"av_same": av_same})

df = pd.DataFrame(
np.concatenate([data[k] for k in data], axis=1),
columns=[k for k in data],
)
rdst = np.random.RandomState(1234567890)  # all the same
# shuffle_truth_colors(df, "tIdx", rdst)

hover_data = ["tIdx", "cellid"] #+ [k for k in hoverdict.keys()]
# if nidx is not None:
#     hover_data.append("av_same")
fig = px.scatter_3d(
df,
x="X",
y="Y",
z="Z",
color="tIdx",
size="features",
hover_data=hover_data,
template="simple_white",
color_continuous_scale=px.colors.sequential.Rainbow,
range_color=[0,30],
)
fig.update_traces(marker=dict(line=dict(width=0)))
fig.update_traces(marker_size = 2)

In [19]:
scatter_sum(torch.ones_like(g.ndata["particle_number"].view(-1)),g.ndata["particle_number"].view(-1).long())

tensor([ 0., 12., 18., 15., 17., 14., 14., 21., 11., 16., 16.,  4., 12., 12.,
        18., 12.,  6., 17.,  8., 11.,  9.,  3.,  3., 10.,  8.,  4.,  7.,  3.,
         9.,  1.,  7.,  4.,  1., 30.,  2.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,
         3.,  5.,  6.,  2.,  1.,  6.,  4.,  1.,  6.,  2., 11.,  6.,  4.,  1.,
         5.,  6.,  1.,  3.,  2.,  1.])

In [20]:
y[:,3]

tensor([ 2.2120e+03, -3.2100e+02,  2.1100e+02, -2.1100e+02,  2.1100e+02,
        -2.1100e+02,  3.2100e+02, -2.1100e+02,  3.2100e+02, -2.1100e+02,
         3.1120e+03,  2.1100e+02, -2.1100e+02,  2.1100e+02, -2.1100e+02,
         1.3000e+02,  2.1100e+02, -2.1100e+02,  2.1100e+02, -2.1100e+02,
        -2.2120e+03,  2.1100e+02,  2.1100e+02, -2.1100e+02,  2.1100e+02,
        -2.1100e+02,  2.2120e+03, -1.3000e+01,  2.1120e+03,  1.1000e+01,
        -1.1000e+01, -1.3000e+01,  1.3000e+01,  1.1000e+01,  1.1000e+01,
         1.1000e+01,  1.1000e+01,  1.1000e+01,  1.1000e+01,  1.1000e+01,
         1.1000e+01,  1.3000e+01,  1.1000e+01, -1.1000e+01,  1.1000e+01,
         2.2120e+03,  2.1100e+02, -1.3000e+01, -2.1100e+02,  2.1100e+02,
         2.2120e+03,  1.1000e+01, -1.1000e+01,  1.1000e+01,  1.0000e+09,
         1.1000e+01, -1.1000e+01,  1.1000e+01,  1.1000e+01,  1.1000e+01,
         1.1000e+01])

In [21]:
y[:,-1]

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.])

In [391]:
from torch_scatter import scatter_add, scatter_sum, scatter_min, scatter_max
coord = g.ndata["pos_hits_xyz"]
cluster_id = g.ndata["particle_number"]
min_x = scatter_min(coord[:, 0], cluster_id.long() - 1)[0]
min_z = scatter_min(coord[:, 2], cluster_id.long() - 1)[0]
min_y = scatter_min(coord[:, 1], cluster_id.long() - 1)[0]
max_x = scatter_max(coord[:, 0], cluster_id.long() - 1)[0]
max_z = scatter_max(coord[:, 2], cluster_id.long() - 1)[0]
max_y = scatter_max(coord[:, 1], cluster_id.long() - 1)[0]
diff_x = torch.abs(max_x - min_x)
diff_z = torch.abs(max_z - min_z)
diff_y = torch.abs(max_y - min_y)
mask_x = diff_x > 2000
mask_z = diff_z > 2800
mask_y = diff_y > 2800
mask_p = mask_x + mask_z + mask_y
mask_p

tensor([ True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False])

In [201]:
diff_x, diff_z,diff_y

(tensor([679.0754,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000]),
 tensor([729.3204,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000]),
 tensor([1783.1533,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000]))